package com.guojianghao.mapper.weixin.autho2;

import com.guojianghao.entity.weixin.autho2.WechatUserinfo;
import com.guojianghao.entity.weixin.autho2.WechatUserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    long countByExample(WechatUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int deleteByExample(WechatUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int insert(WechatUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int insertSelective(WechatUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    List<WechatUserinfo> selectByExample(WechatUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    WechatUserinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int updateByExampleSelective(@Param("record") WechatUserinfo record, @Param("example") WechatUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int updateByExample(@Param("record") WechatUserinfo record, @Param("example") WechatUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int updateByPrimaryKeySelective(WechatUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_userinfo
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    int updateByPrimaryKey(WechatUserinfo record);
}