package com.guojianghao.entity.weixin.autho2;

public class WechatUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.id
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.openid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.nickname
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.sex
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.province
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.city
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.country
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.headimgurl
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.privilege
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String privilege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_userinfo.unionid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    private String unionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.id
     *
     * @return the value of wechat_userinfo.id
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.id
     *
     * @param id the value for wechat_userinfo.id
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.openid
     *
     * @return the value of wechat_userinfo.openid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.openid
     *
     * @param openid the value for wechat_userinfo.openid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.nickname
     *
     * @return the value of wechat_userinfo.nickname
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.nickname
     *
     * @param nickname the value for wechat_userinfo.nickname
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.sex
     *
     * @return the value of wechat_userinfo.sex
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.sex
     *
     * @param sex the value for wechat_userinfo.sex
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.province
     *
     * @return the value of wechat_userinfo.province
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.province
     *
     * @param province the value for wechat_userinfo.province
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.city
     *
     * @return the value of wechat_userinfo.city
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.city
     *
     * @param city the value for wechat_userinfo.city
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.country
     *
     * @return the value of wechat_userinfo.country
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.country
     *
     * @param country the value for wechat_userinfo.country
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.headimgurl
     *
     * @return the value of wechat_userinfo.headimgurl
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.headimgurl
     *
     * @param headimgurl the value for wechat_userinfo.headimgurl
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.privilege
     *
     * @return the value of wechat_userinfo.privilege
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.privilege
     *
     * @param privilege the value for wechat_userinfo.privilege
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_userinfo.unionid
     *
     * @return the value of wechat_userinfo.unionid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_userinfo.unionid
     *
     * @param unionid the value for wechat_userinfo.unionid
     *
     * @mbg.generated Sat Oct 07 11:30:49 SGT 2017
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }
}